### PR TITLE
Added proxy support based on env variables

### PR DESCRIPTION
**Pull request by svarcheg**
Avoids "Connection refused" if called from behind a corporate proxy. Fixed it to work, created a PR just in case, if others are interesed

### CODE REVIEW

**Comment by hyPiRion** [comment]
Looks good, thanks!

**Comment by beickhoff** [comment]
What about a fallback to an environment variable instead of system properties, i.e. `System.getenv("http_proxy")`?

**Comment by hyPiRion** [comment]
Happy to merge in an implementation which uses environment variables just like Leiningen does.

It's probably desirable to have this propagate down to the daemon itself as well, so that dependency fetching is also done through a proxy; am I right?

**Comment by svarcheg** [comment]
hi guys, 

first,  inlein is a wonderful tool thanks for writing it ;) 

i didnt experience any issues with daemon (still behind a corporate proxy). Maybe the daemon network tooling already supports http proxy vars out of the box? i didn't check that as it worked for me.

@beickhoff  true, this was a working quickfix on my box but indeed i have proxy data pushed into java properties, will put myself a task to get back to this one

Kind regards, 

Vladimir

**Comment by hyPiRion** [comment]
Alright, thanks for verifying – I guess Aether (dependency fetcher) just picks up the default Java proxy options.

**Pull request merged**
